package com.mycompany.testproject.model;
// Generated 06.09.2016 1:52:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Part generated by hbm2java
 */
public class Part  implements java.io.Serializable {


     private String name;
     private String number;
     private String vendor;
     private Integer qty;
     private Date shipped;
     private Date receive;

    public Part() {
    }

	
    public Part(String name) {
        this.name = name;
    }
    public Part(String name, String number, String vendor, Integer qty, Date shipped, Date receive) {
       this.name = name;
       this.number = number;
       this.vendor = vendor;
       this.qty = qty;
       this.shipped = shipped;
       this.receive = receive;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Date getShipped() {
        return this.shipped;
    }
    
    public void setShipped(Date shipped) {
        this.shipped = shipped;
    }
    public Date getReceive() {
        return this.receive;
    }
    
    public void setReceive(Date receive) {
        this.receive = receive;
    }




}


